DROP TABLE IF EXISTS `fof_cities`;
CREATE TABLE  `fof_cities` (
  `ID` int(10) unsigned NOT NULL,
  `Name` varchar(45) NOT NULL,
  `Abbrev` char(3) NOT NULL,
  `Pop` bigint(20) unsigned NOT NULL,
  `Growth` float NOT NULL,
  `AvgInc` int(10) unsigned NOT NULL,
  `PovLevel` float NOT NULL,
  `EntComp` tinyint(3) unsigned NOT NULL,
  `SeptHi` smallint(5) NOT NULL,
  `SeptLo` smallint(5) NOT NULL,
  `SeptHum` tinyint(3) unsigned NOT NULL,
  `DecHi` smallint(5) NOT NULL,
  `DecLo` smallint(5) NOT NULL,
  `DecHum` tinyint(3) unsigned NOT NULL,
  `NinetyDegDays` smallint(5) unsigned NOT NULL,
  `SnowDays` smallint(5) unsigned NOT NULL,
  `StormDays` smallint(5) unsigned NOT NULL,
  `Elev` smallint(5) unsigned NOT NULL,
  `Longitude` float NOT NULL,
  `Latitude` float NOT NULL,
  `Region` tinyint(3) unsigned NOT NULL,
  `State` tinyint(3) unsigned NOT NULL,
  `WantsTeam` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS `fof_colleges`;
CREATE TABLE  `fof_colleges` (
  `ID` smallint(5) unsigned NOT NULL,
  `Name` varchar(128) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

DROP TABLE IF EXISTS `fof_franchise`;
CREATE TABLE  `fof_franchise` (
  `ID` smallint(5) NOT NULL auto_increment,
  `TeamIndex` tinyint(3) unsigned NOT NULL,
  `Year` smallint(5) unsigned NOT NULL,
  `FranchiseValue` tinyint(3) unsigned NOT NULL,
  `ProfitScore` tinyint(3) unsigned NOT NULL,
  `PerformanceScore` tinyint(3) unsigned NOT NULL,
  `RosterScore` tinyint(3) unsigned NOT NULL,
  `Playoffs` tinyint(3) unsigned NOT NULL,
  `Wins` tinyint(3) unsigned NOT NULL,
  `Losses` tinyint(3) unsigned NOT NULL,
  `Ties` tinyint(3) unsigned NOT NULL,
  `PointsFor` smallint(5) unsigned NOT NULL,
  `PointsAgainst` smallint(5) unsigned NOT NULL,
  `ConfWins` tinyint(3) unsigned NOT NULL,
  `ConfLoss` tinyint(3) unsigned NOT NULL,
  `ConfTies` tinyint(3) unsigned NOT NULL,
  `DivWin` tinyint(3) unsigned NOT NULL,
  `DivLoss` tinyint(3) unsigned NOT NULL,
  `DivTie` tinyint(3) unsigned NOT NULL,
  `Attendance` int(10) unsigned NOT NULL,
  `StadiumCapacity` int(10) unsigned NOT NULL,
  `TVRevenue` bigint(20) unsigned NOT NULL,
  `TicketRevenue` bigint(20) unsigned NOT NULL,
  `SuiteRevenue` bigint(20) unsigned NOT NULL,
  `PlayerSalaries` bigint(20) unsigned NOT NULL,
  `PlayerBonuses` bigint(20) unsigned NOT NULL,
  `StadiumPayment` bigint(20) unsigned NOT NULL,
  `Concessions` bigint(20) unsigned NOT NULL,
  `Parking` bigint(20) unsigned NOT NULL,
  `Advertising` bigint(20) unsigned NOT NULL,
  `Training` bigint(20) unsigned NOT NULL,
  `Coaching` bigint(20) unsigned NOT NULL,
  `Scouting` bigint(20) unsigned NOT NULL,
  `Maintenance` bigint(20) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_gameinfo`;
CREATE TABLE  `fof_gameinfo` (
  `ID` smallint(5) NOT NULL auto_increment,
  `StartYear` smallint(5) unsigned NOT NULL,
  `CurYear` smallint(5) unsigned NOT NULL,
  `Stage` tinyint(3) unsigned NOT NULL,
  `Week` tinyint(3) unsigned NOT NULL,
  `FAStage` tinyint(3) unsigned NOT NULL,
  `PlayerTeam` tinyint(3) unsigned NOT NULL,
  `TeamCount` tinyint(3) unsigned NOT NULL,
  `SalaryCap` bigint(20) unsigned NOT NULL,
  `MinSalary` bigint(20) unsigned NOT NULL,
  `SchemaVersion` smallint(5) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_gameresults`;
CREATE TABLE  `fof_gameresults` (
  `ID` int(10) NOT NULL AUTO_INCREMENT,
  `Year` smallint(5) unsigned NOT NULL,
  `Week` tinyint(3) unsigned NOT NULL,
  `AwayScore` tinyint(3) unsigned NOT NULL,
  `AwayTeam` tinyint(3) unsigned NOT NULL,
  `HomeScore` tinyint(3) unsigned NOT NULL,
  `HomeTeam` tinyint(3) unsigned NOT NULL,
  `Attendance` int(10) unsigned NOT NULL,
  `Temperature` smallint(5) NOT NULL,
  `Precip` tinyint(3) unsigned NOT NULL,
  `Wind` tinyint(3) unsigned NOT NULL,
  `AwayPassingLeaderPlayerID` int(10) unsigned NOT NULL,
  `HomePassingLeaderPlayerID` int(10) unsigned NOT NULL,
  `AwayRushingLeaderPlayerID` int(10) unsigned NOT NULL,
  `HomeRushingLeaderPlayerID` int(10) unsigned NOT NULL,
  `AwayReceivingLeaderPlayerID` int(10) unsigned NOT NULL,
  `HomeReceivingLeaderPlayerID` int(10) unsigned NOT NULL,
  `AwayPassAttempts` tinyint(3) unsigned NOT NULL,
  `AwayPassCompletions` tinyint(3) unsigned NOT NULL,
  `AwayPassYards` smallint(5) NOT NULL,
  `HomePassAttempts` tinyint(3) unsigned NOT NULL,
  `HomePassCompletions` tinyint(3) unsigned NOT NULL,
  `HomePassYards` smallint(5) NOT NULL,
  `AwayRushAttempts` tinyint(3) unsigned NOT NULL,
  `AwayRushYards` smallint(5) NOT NULL,
  `HomeRushAttempts` tinyint(3) unsigned NOT NULL,
  `HomeRushYards` smallint(5) NOT NULL,
  `AwayReceptions` tinyint(3) unsigned NOT NULL,
  `AwayReceivingYards` smallint(5) NOT NULL,
  `HomeReceptions` tinyint(3) unsigned NOT NULL,
  `HomeReceivingYards` smallint(5) NOT NULL,
  `PlayerOfTheGame` int(10) unsigned NOT NULL,
  `HomeScreenAttempts` tinyint(3) unsigned NOT NULL,
  `HomeScreenCompletions` tinyint(3) unsigned NOT NULL,
  `HomeScreenYards` smallint(6) NOT NULL,
  `HomeShortAttempts` tinyint(3) unsigned NOT NULL,
  `HomeShortCompletions` tinyint(3) unsigned NOT NULL,
  `HomeShortYards` smallint(6) NOT NULL,
  `HomeMediumAttempts` tinyint(3) unsigned NOT NULL,
  `HomeMediumCompletions` tinyint(3) unsigned NOT NULL,
  `HomeMediumYards` smallint(6) NOT NULL,
  `HomeLongAttempts` tinyint(3) unsigned NOT NULL,
  `HomeLongCompletions` tinyint(3) unsigned NOT NULL,
  `HomeLongYards` smallint(6) NOT NULL,
  `HomeOtherAttempts` tinyint(3) unsigned NOT NULL,
  `HomeOtherCompletions` tinyint(3) unsigned NOT NULL,
  `HomeOtherYards` smallint(6) NOT NULL,
  `AwayScreenAttempts` tinyint(3) unsigned NOT NULL,
  `AwayScreenCompletions` tinyint(3) unsigned NOT NULL,
  `AwayScreenYards` smallint(6) NOT NULL,
  `AwayShortAttempts` tinyint(3) unsigned NOT NULL,
  `AwayShortCompletions` tinyint(3) unsigned NOT NULL,
  `AwayShortYards` smallint(6) NOT NULL,
  `AwayMediumAttempts` tinyint(3) unsigned NOT NULL,
  `AwayMediumCompletions` tinyint(3) unsigned NOT NULL,
  `AwayMediumYards` smallint(6) NOT NULL,
  `AwayLongAttempts` tinyint(3) unsigned NOT NULL,
  `AwayLongCompletions` tinyint(3) unsigned NOT NULL,
  `AwayLongYards` smallint(6) NOT NULL,
  `AwayOtherAttempts` tinyint(3) unsigned NOT NULL,
  `AwayOtherCompletions` tinyint(3) unsigned NOT NULL,
  `AwayOtherYards` smallint(6) NOT NULL,
  `HomeLeftRushAttempts` tinyint(3) unsigned NOT NULL,
  `HomeLeftRushYards` smallint(6) NOT NULL,
  `HomeMiddleRushAttempts` tinyint(3) unsigned NOT NULL,
  `HomeMiddleRushYards` smallint(6) NOT NULL,
  `HomeRightRushAttempts` tinyint(3) unsigned NOT NULL,
  `HomeRightRushYards` smallint(6) NOT NULL,
  `HomeOtherRushAttempts` tinyint(3) unsigned NOT NULL,
  `HomeOtherRushYards` smallint(6) NOT NULL,
  `AwayLeftRushAttempts` tinyint(3) unsigned NOT NULL,
  `AwayLeftRushYards` smallint(6) NOT NULL,
  `AwayMiddleRushAttempts` tinyint(3) unsigned NOT NULL,
  `AwayMiddleRushYards` smallint(6) NOT NULL,
  `AwayRightRushAttempts` tinyint(3) unsigned NOT NULL,
  `AwayRightRushYards` smallint(6) NOT NULL,
  `AwayOtherRushAttempts` tinyint(3) unsigned NOT NULL,
  `AwayOtherRushYards` smallint(6) NOT NULL,
  `HomeTimeOfPossession` smallint(5) unsigned NOT NULL,
  `HomeRedZoneAttempts` tinyint(3) unsigned NOT NULL,
  `HomeRedZoneTDs` tinyint(3) unsigned NOT NULL,
  `HomeRedZoneFGs` tinyint(3) unsigned NOT NULL,
  `AwayTimeOfPossession` smallint(5) unsigned NOT NULL,
  `AwayRedZoneAttempts` tinyint(3) unsigned NOT NULL,
  `AwayRedZoneTDs` tinyint(3) unsigned NOT NULL,
  `AwayRedZoneFGs` tinyint(3) unsigned NOT NULL,
  `TotalCapacity` int(10) unsigned NOT NULL,
  `UpperDeckAttendance` int(10) unsigned NOT NULL,
  `UpperDeckCapacity` int(10) unsigned NOT NULL,
  `EndZoneAttendance` int(10) unsigned NOT NULL,
  `EndZoneCapacity` int(10) unsigned NOT NULL,
  `MezzanineAttendance` int(10) unsigned NOT NULL,
  `MezzanineCapacity` int(10) unsigned NOT NULL,
  `SidelineAttendance` int(10) unsigned NOT NULL,
  `SidelineCapacity` int(10) unsigned NOT NULL,
  `ClubAttendance` int(10) unsigned NOT NULL,
  `ClubCapacity` int(10) unsigned NOT NULL,
  `BoxAttendance` int(10) unsigned NOT NULL,
  `BoxCapacity` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_gamedrive`;
CREATE TABLE  `fof_gamedrive` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `StartQuarter` tinyint(3) unsigned NOT NULL,
  `StartMinutes` tinyint(3) unsigned NOT NULL,
  `StartSeconds` tinyint(3) unsigned NOT NULL,
  `EndQuarter` tinyint(3) unsigned NOT NULL,
  `EndMinutes` tinyint(3) unsigned NOT NULL,
  `EndSeconds` tinyint(3) unsigned NOT NULL,
  `StartYardsFromGoal` tinyint(3) unsigned NOT NULL,
  `PlayCount` tinyint(3) unsigned NOT NULL,
  `YardsGained` smallint(6) NOT NULL,
  `Result` tinyint(3) unsigned NOT NULL,
  `GameID` int(10) unsigned NOT NULL,
  `Team` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_hometowns`;
CREATE TABLE  `fof_hometowns` (
  `ID` smallint(5) unsigned NOT NULL,
  `Name` varchar(128) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

DROP TABLE IF EXISTS `fof_injuries`;
CREATE TABLE  `fof_injuries` (
  `ID` smallint(5) unsigned NOT NULL,
  `Name` varchar(128) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

DROP TABLE IF EXISTS `fof_mappings`;
CREATE TABLE  `fof_mappings` (
  `ID` smallint(5) unsigned NOT NULL,
  `Position` char(4) NOT NULL,
  `PositionGroup` char(3) NOT NULL,
  `TransactionType` varchar(64) NOT NULL,
  `Precipitation` varchar(10) NOT NULL,
  `PlayerStatus` varchar(20) NOT NULL,
  `StaffRole` varchar(20) NOT NULL,
  `Playoffs` varchar(20) NOT NULL,
  `Ability` varchar(12) NOT NULL,
  `StadiumType` varchar(25) NOT NULL,
  `ConstructionType` varchar(15) NOT NULL,
  `DriveResult` varchar(15) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 ROW_FORMAT=FIXED;

DROP TABLE IF EXISTS `fof_playeractive`;
CREATE TABLE  `fof_playeractive` (
  `ID` int(10) NOT NULL,
  `Position` tinyint(3) unsigned NOT NULL,
  `Experience` tinyint(3) unsigned NOT NULL,
  `Number` tinyint(3) unsigned NOT NULL,
  `PositionGroup` tinyint(3) unsigned NOT NULL,
  `Team` tinyint(3) unsigned NOT NULL,
  `InjuryLength` smallint(5) unsigned NOT NULL,
  `Loyalty` tinyint(3) unsigned NOT NULL,
  `PlaysToWin` tinyint(3) unsigned NOT NULL,
  `Personality` tinyint(3) unsigned NOT NULL,
  `Leadership` tinyint(3) unsigned NOT NULL,
  `Intelligence` tinyint(3) unsigned NOT NULL,
  `RedFlagMarker` tinyint(1) unsigned NOT NULL,
  `Volatility` tinyint(3) unsigned NOT NULL,
  `JoinedTeam` smallint(5) unsigned NOT NULL,
  `UFAYear` smallint(5) unsigned NOT NULL,
  `Popularity` tinyint(3) unsigned NOT NULL,
  `ContractLength` tinyint(3) unsigned NOT NULL,
  `Salary1` bigint(20) unsigned NOT NULL,
  `Salary2` bigint(20) unsigned NOT NULL,
  `Salary3` bigint(20) unsigned NOT NULL,
  `Salary4` bigint(20) unsigned NOT NULL,
  `Salary5` bigint(20) unsigned NOT NULL,
  `Salary6` bigint(20) unsigned NOT NULL,
  `Salary7` bigint(20) unsigned NOT NULL,
  `Bonus1` bigint(20) unsigned NOT NULL,
  `Bonus2` bigint(20) unsigned NOT NULL,
  `Bonus3` bigint(20) unsigned NOT NULL,
  `Bonus4` bigint(20) unsigned NOT NULL,
  `Bonus5` bigint(20) unsigned NOT NULL,
  `Bonus6` bigint(20) unsigned NOT NULL,
  `Bonus7` bigint(20) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_playergamestats`;
CREATE TABLE  `fof_playergamestats` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `PlayerID` int(10) unsigned NOT NULL,
  `Year` smallint(5) unsigned NOT NULL,
  `Week` tinyint(3) unsigned NOT NULL,
  `Team` tinyint(3) unsigned NOT NULL,
  `GamePlayed` tinyint(1) unsigned NOT NULL,
  `GameStarted` tinyint(1) unsigned NOT NULL,
  `PassAttempts` tinyint(3) unsigned NOT NULL,
  `PassCompletions` tinyint(3) unsigned NOT NULL,
  `PassYards` smallint(5) NOT NULL,
  `LongestPass` smallint(5) NOT NULL,
  `TDPasses` tinyint(3) unsigned NOT NULL,
  `INTThrown` tinyint(3) unsigned NOT NULL,
  `TimesSacked` tinyint(3) unsigned NOT NULL,
  `SackedYards` smallint(5) unsigned NOT NULL,
  `RushAttempts` tinyint(3) unsigned NOT NULL,
  `RushingYards` smallint(5) NOT NULL,
  `LongestRun` smallint(5) NOT NULL,
  `RushTD` tinyint(3) unsigned NOT NULL,
  `Catches` tinyint(3) unsigned NOT NULL,
  `ReceivingYards` smallint(5) NOT NULL,
  `LongestReception` smallint(5) NOT NULL,
  `ReceivingTDs` tinyint(3) unsigned NOT NULL,
  `PassTargets` tinyint(3) unsigned NOT NULL,
  `YardsAfterCatch` smallint(5) NOT NULL,
  `PassDrops` tinyint(3) unsigned NOT NULL,
  `PuntReturns` tinyint(3) unsigned NOT NULL,
  `PuntReturnYards` smallint(5) NOT NULL,
  `PuntReturnTDs` tinyint(3) unsigned NOT NULL,
  `KickReturns` tinyint(3) unsigned NOT NULL,
  `KickReturnYards` smallint(5) NOT NULL,
  `KickReturnTDs` tinyint(3) unsigned NOT NULL,
  `Fumbles` tinyint(3) unsigned NOT NULL,
  `FumbleRecoveries` tinyint(3) unsigned NOT NULL,
  `ForcedFumbles` tinyint(3) unsigned NOT NULL,
  `MiscTD` tinyint(3) unsigned NOT NULL,
  `KeyRunBlock` tinyint(3) unsigned NOT NULL,
  `KeyRunBlockOpportunites` tinyint(3) unsigned NOT NULL,
  `SacksAllowed` tinyint(3) unsigned NOT NULL,
  `Tackles` tinyint(3) unsigned NOT NULL,
  `Assists` tinyint(3) unsigned NOT NULL,
  `Sacks` smallint(5) unsigned NOT NULL,
  `INTs` tinyint(3) unsigned NOT NULL,
  `INTReturnYards` smallint(5) NOT NULL,
  `INTReturnTDs` tinyint(3) unsigned NOT NULL,
  `PassesDefended` tinyint(3) unsigned NOT NULL,
  `PassesBlocked` tinyint(3) unsigned NOT NULL,
  `QBHurries` tinyint(3) unsigned NOT NULL,
  `PassesCaught` tinyint(3) unsigned NOT NULL,
  `PassPlays` tinyint(3) unsigned NOT NULL,
  `RunPlays` tinyint(3) unsigned NOT NULL,
  `FGMade` tinyint(3) unsigned NOT NULL,
  `FGAttempted` tinyint(3) unsigned NOT NULL,
  `FGLong` tinyint(3) unsigned NOT NULL,
  `PAT` tinyint(3) unsigned NOT NULL,
  `PATAttempted` tinyint(3) unsigned NOT NULL,
  `Punts` tinyint(3) unsigned NOT NULL,
  `PuntYards` smallint(5) unsigned NOT NULL,
  `PuntLong` smallint(5) NOT NULL,
  `PuntIn20` tinyint(3) unsigned NOT NULL,
  `Points` tinyint(3) unsigned NOT NULL,
  `OpposingTeamID` tinyint(3) unsigned NOT NULL,
  `ThirdDownRushes` tinyint(3) unsigned NOT NULL,
  `ThirdDownRushConversions` tinyint(3) unsigned NOT NULL,
  `ThirdDownPassAttempts` tinyint(3) unsigned NOT NULL,
  `ThirdDownPassCompletions` tinyint(3) unsigned NOT NULL,
  `ThirdDownPassConversions` tinyint(3) unsigned NOT NULL,
  `ThirdDownReceivingTargets` tinyint(3) unsigned NOT NULL,
  `ThirdDownReceivingCatches` tinyint(3) unsigned NOT NULL,
  `ThirdDownReceivingConversions` tinyint(3) unsigned NOT NULL,
  `FirstDownRushes` tinyint(3) unsigned NOT NULL,
  `FirstDownPasses` tinyint(3) unsigned NOT NULL,
  `FirstDownCatches` tinyint(3) unsigned NOT NULL,
  `FG40PlusAttempts` tinyint(3) unsigned NOT NULL,
  `FG40PlusMade` tinyint(3) unsigned NOT NULL,
  `FG50PlusAttempts` tinyint(3) unsigned NOT NULL,
  `FG50PlusMade` tinyint(3) unsigned NOT NULL,
  `PuntNetYards` smallint(5) NOT NULL,
  `SpecialTeamsTackles` tinyint(3) unsigned NOT NULL,
  `TimesKnockedDown` tinyint(3) unsigned NOT NULL,
  `RedZoneRushes` tinyint(3) unsigned NOT NULL,
  `RedZoneRushingYards` smallint(5) NOT NULL,
  `RedZonePassAttempts` tinyint(3) unsigned NOT NULL,
  `RedZonePassCompletions` tinyint(3) unsigned NOT NULL,
  `RedZonePassingYards` smallint(5) NOT NULL,
  `RedZoneReceivingTargets` tinyint(3) unsigned NOT NULL,
  `RedZoneReceivingCatches` tinyint(3) unsigned NOT NULL,
  `RedZoneReceivingYards` smallint(5) NOT NULL,
  `TotalTDs` tinyint(3) unsigned NOT NULL,
  `TwoPointConversions` tinyint(3) unsigned NOT NULL,
  `PancakeBlocks` tinyint(3) unsigned NOT NULL,
  `QBKnockdowns` tinyint(3) unsigned NOT NULL,
  `SpecialTeamsPlays` tinyint(3) unsigned NOT NULL,
  `RushingGamesOver100Yards` tinyint(3) unsigned NOT NULL,
  `ReceivingGamesOver100Yards` tinyint(3) unsigned NOT NULL,
  `PassingGamesOver300Yards` tinyint(3) unsigned NOT NULL,
  `RunsOf10YardsPlus` tinyint(3) unsigned NOT NULL,
  `CatchesOf20YardsPlus` tinyint(3) unsigned NOT NULL,
  `ThrowsOf20YardsPlus` tinyint(3) unsigned NOT NULL,
  `AllPurposeYards` smallint(5) NOT NULL,
  `YardsFromScrimmage` smallint(5) NOT NULL,
  `DoubleCoveragesThrownInto` tinyint(3) unsigned NOT NULL,
  `DoubleCoveragesAvoided` tinyint(3) unsigned NOT NULL,
  `BadPasses` tinyint(3) unsigned NOT NULL,
  `RunsForLoss` tinyint(3) unsigned NOT NULL,
  `RunsOf20YardsPlus` tinyint(3) unsigned NOT NULL,
  `FumblesLost` tinyint(3) unsigned NOT NULL,
  `HasKeyCoverage` tinyint(3) unsigned NOT NULL,
  `ThrownAt` tinyint(3) unsigned NOT NULL,
  `TacklesForLoss` tinyint(3) unsigned NOT NULL,
  `AssistedTacklesForLoss` tinyint(3) unsigned NOT NULL,
  `ReceptionsOf20YardsPlusGivenUp` tinyint(3) unsigned NOT NULL,
  `Kickoffs` tinyint(3) unsigned NOT NULL,
  `KickoffYards` smallint(5) NOT NULL,
  `KickoffTouchbacks` tinyint(3) unsigned NOT NULL,
  `TotalFieldPositionAfterKickoff` smallint(5) unsigned NOT NULL,
  `OffensivePassPlays` tinyint(3) unsigned NOT NULL,
  `OffensiveRunPlays` tinyint(3) unsigned NOT NULL,
  `DefensivePassPlays` tinyint(3) unsigned NOT NULL,
  `DefensiveRunPlays` tinyint(3) unsigned NOT NULL,
  `SuccessfulPasses` tinyint(3) unsigned NOT NULL,
  `SuccessfulCatches` tinyint(3) unsigned NOT NULL,
  `SuccessfulRuns` tinyint(3) unsigned NOT NULL,
  `BadPassesCaught` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_playerhistorical`;
CREATE TABLE  `fof_playerhistorical` (
  `ID` int(10) NOT NULL,
  `Position` tinyint(3) unsigned NOT NULL,
  `LastName` varchar(128) NOT NULL,
  `FirstName` varchar(128) NOT NULL,
  `NickName` varchar(128) NOT NULL,
  `Experience` tinyint(3) unsigned NOT NULL,
  `Height` tinyint(3) unsigned NOT NULL,
  `Weight` smallint(5) unsigned NOT NULL,
  `InHallOfFame` tinyint(3) unsigned NOT NULL,
  `HallOfFameYear` smallint(5) unsigned NOT NULL,
  `HallOfFameVote` tinyint(3) unsigned NOT NULL,
  `BirthYear` smallint(5) unsigned NOT NULL,
  `BirthMonth` tinyint(2) unsigned NOT NULL,
  `BirthDay` tinyint(2) unsigned NOT NULL,
  `College` smallint(5) unsigned NOT NULL,
  `DraftRound` tinyint(3) unsigned NOT NULL,
  `DraftPick` tinyint(3) unsigned NOT NULL,
  `HomeTown` smallint(5) unsigned NOT NULL,
  `DraftedBy` tinyint(3) unsigned NOT NULL,
  `YearDraft` smallint(5) unsigned NOT NULL,
  `YearRetired` smallint(5) unsigned NOT NULL,
  `PoG` smallint(5) unsigned NOT NULL,
  `Rings` smallint(5) unsigned NOT NULL,
  `PoWMentions` smallint(5) unsigned NOT NULL,
  `PoWWins` smallint(5) unsigned NOT NULL,
  `FourQHero` smallint(5) unsigned NOT NULL,
  `QBWins` smallint(5) unsigned NOT NULL,
  `QBLosses` smallint(5) unsigned NOT NULL,
  `QBTies` smallint(5) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_stagenames`;
CREATE TABLE  `fof_stagenames` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `StageName` varchar(45) NOT NULL,
  `StageIndex` tinyint(3) unsigned NOT NULL,
  `GameInfoStage` tinyint(3) unsigned NOT NULL,
  `GameInfoWeek` tinyint(3) unsigned NOT NULL,
  `GameInfoFAStage` tinyint(3) unsigned NOT NULL,
  `TransactionStage` smallint(5) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_teams`;
CREATE TABLE  `fof_teams` (
  `ID` smallint(5) NOT NULL default '0',
  `Nickname` varchar(20) NOT NULL default '',
  `CityName` varchar(45) NOT NULL,
  `Abbrev` char(3) NOT NULL,
  `CityID` smallint(5) unsigned NOT NULL,
  `Conference` tinyint(3) unsigned NOT NULL,
  `Division` tinyint(3) unsigned NOT NULL,
  `CapLossThisYear` bigint(20) unsigned NOT NULL,
  `CapLossNextYear` bigint(20) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_teamschedule`;
CREATE TABLE  `fof_teamschedule` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `TeamID` tinyint(3) unsigned NOT NULL,
  `Week` tinyint(1) unsigned NOT NULL,
  `Away` tinyint(1) unsigned NOT NULL,
  `ConferenceGame` smallint(5) unsigned NOT NULL,
  `DivisionGame` smallint(5) unsigned NOT NULL,
  `OpponentID` tinyint(3) unsigned NOT NULL,
  `Score` tinyint(3) unsigned NOT NULL,
  `OppScore` tinyint(3) unsigned NOT NULL,
  `Attendance` int(10) unsigned NOT NULL,
  `Temperature` smallint(5) NOT NULL,
  `Precip` tinyint(3) unsigned NOT NULL,
  `Wind` tinyint(3) unsigned NOT NULL,
  `Year` smallint(5) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_teamstadium`;
CREATE TABLE  `fof_teamstadium` (
  `TeamID` smallint(5) NOT NULL default '0',
  `StadiumType` tinyint(3) unsigned NOT NULL,
  `YearStadiumBuilt` smallint(5) unsigned NOT NULL,
  `TotalCapacity` int(10) unsigned NOT NULL,
  `LuxuryBoxes` smallint(5) unsigned NOT NULL,
  `ClubSeats` int(10) unsigned NOT NULL,
  `FanLoyalty` tinyint(3) unsigned NOT NULL,
  `PublicSupport` tinyint(3) unsigned NOT NULL,
  `UpperDeckPrice` smallint(5) unsigned NOT NULL,
  `EndZonePrice` smallint(5) unsigned NOT NULL,
  `MezzaninePrice` smallint(5) unsigned NOT NULL,
  `SidelinesPrice` smallint(5) unsigned NOT NULL,
  `ClubSeatsPrice` smallint(5) unsigned NOT NULL,
  `LuxuryBoxPrice` int(10) unsigned NOT NULL,
  `ConstructionCompleteYear` smallint(5) unsigned NOT NULL,
  `ConstructionType` tinyint(3) unsigned NOT NULL,
  `ConstructionCapacity` int(10) unsigned NOT NULL,
  `ConstructionLuxuryBoxes` smallint(5) unsigned NOT NULL,
  `ConstructionClubSeats` int(10) unsigned NOT NULL,
  `ConstructionStadiumType` tinyint(3) unsigned NOT NULL,
  `PriorYearAttendance` int(10) unsigned NOT NULL,
  PRIMARY KEY  (`TeamID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_transactions`;
CREATE TABLE  `fof_transactions` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `InSeasonIndex` int(10) unsigned NOT NULL,
  `PrimaryIndex` int(10) unsigned NOT NULL,
  `Salary` int(10) unsigned NOT NULL,
  `Type` tinyint(3) unsigned NOT NULL,
  `Team1ID` smallint(5) unsigned NOT NULL,
  `Team2ID` int(10) unsigned NOT NULL,
  `Position` smallint(5) unsigned NOT NULL,
  `Years` smallint(5) unsigned NOT NULL,
  `Stage` smallint(5) unsigned NOT NULL,
  `Season` smallint(5) unsigned NOT NULL,
  `PlayerID` int(10) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fof_futuredrafts`;
CREATE TABLE  `fof_futuredrafts` (
  `ID` int(10) unsigned NOT NULL auto_increment,
  `Year` smallint(5) unsigned NOT NULL,
  `Round` smallint(5) unsigned NOT NULL,
  `Pick` smallint(5) unsigned NOT NULL,
  `TeamID` smallint(5) unsigned NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
