ALTER TABLE `fof_playergamestats` ADD COLUMN  `DoubleCoveragesThrownInto` tinyint(3) unsigned NOT NULL AFTER `YardsFromScrimmage`,
  ADD COLUMN  `DoubleCoveragesAvoided` tinyint(3) unsigned NOT NULL AFTER `DoubleCoveragesThrownInto`,
  ADD COLUMN  `BadPasses` tinyint(3) unsigned NOT NULL AFTER `DoubleCoveragesAvoided`,
  ADD COLUMN  `RunsForLoss` tinyint(3) unsigned NOT NULL AFTER `BadPasses`,
  ADD COLUMN  `RunsOf20YardsPlus` tinyint(3) unsigned NOT NULL AFTER `RunsForLoss`,
  ADD COLUMN  `FumblesLost` tinyint(3) unsigned NOT NULL AFTER `RunsOf20YardsPlus`,
  ADD COLUMN  `HasKeyCoverage` tinyint(3) unsigned NOT NULL AFTER `FumblesLost`,
  ADD COLUMN  `ThrownAt` tinyint(3) unsigned NOT NULL AFTER `HasKeyCoverage`,
  ADD COLUMN  `TacklesForLoss` tinyint(3) unsigned NOT NULL AFTER `ThrownAt`,
  ADD COLUMN  `ReceptionsOf20YardsPlusGivenUp` tinyint(3) unsigned NOT NULL AFTER `TacklesForLoss`,
  ADD COLUMN  `Kickoffs` tinyint(3) unsigned NOT NULL AFTER `ReceptionsOf20YardsPlusGivenUp`,
  ADD COLUMN  `KickoffYards` smallint(5) NOT NULL AFTER `Kickoffs`,
  ADD COLUMN  `KickoffTouchbacks` tinyint(3) unsigned NOT NULL AFTER `KickoffYards`,
  ADD COLUMN  `AverageFieldPositionAfterKickoff` tinyint(3) unsigned NOT NULL AFTER `KickoffTouchbacks`;